# Generated by Django 5.0.3 on 2024-03-09 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_loginlogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginLogs',
            new_name='LoginTryLogs',
        ),
    ]
